/**
 * Seeds clearly-labelled DEMONSTRATION records into the live database.
 *
 * Design rules (these are the reason this file was rewritten):
 *
 *  1. NO geography is written by this script. State / district / tehsil /
 *     village values and their LGD codes are resolved at run time through
 *     `administrativeGeographyService` — the same service the API and the UI
 *     use. A hardcoded "Maharashtra / Pune / Maval" string here would be
 *     fabricated geography, and it would silently disagree with whatever the
 *     authoritative source actually contains.
 *
 *  2. If no hierarchy has been ingested, `acquisition_cases.state/district/
 *     village` are NOT NULL columns, so this script refuses to create cases
 *     and says so. It never invents values to satisfy the schema.
 *
 *  3. Everything it does create is explicitly labelled as demonstration data
 *     in the record itself (title, description, actor names and event
 *     metadata), and it flows through the ordinary workflow engine, audit
 *     log, notifications and analytics paths — no frontend-only fake arrays.
 *
 *  4. It is idempotent and deterministic: re-running it changes nothing, and
 *     no identifiers are randomised.
 *
 * Run: bun run scripts/seed.ts
 */
import dotenv from 'dotenv';
import path from 'path';
import { createClient } from '@supabase/supabase-js';
import { initializeCaseWorkflow, advanceStageInstance } from '../server/services/workflowEngine';
import {
  getGeographyProvenance,
  getStates,
  getDistricts,
  getSubDistricts,
  getVillages,
} from '../server/services/administrativeGeographyService';
import type { AdministrativeUnit } from '../shared/types';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const supabaseKey =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.SUPABASE_ANON_KEY ||
  process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey || supabaseUrl.includes('your-supabase-project')) {
  console.error('\nERROR: Supabase credentials not found in .env!');
  console.error(
    'Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env before running the seed.\n'
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const DEMO_LABEL = 'Demonstration';
const DEMO_ACTOR = 'Demonstration seed (sample data)';
const DEMO_NOTE =
  '[DEMONSTRATION RECORD — sample data generated by scripts/seed.ts to exercise the real workflow, ' +
  'audit, notification and analytics paths. This is not a real land acquisition.]';

const byCode = (a: AdministrativeUnit, b: AdministrativeUnit) =>
  a.code.localeCompare(b.code, 'en', { numeric: true });

/** A fully resolved state -> district -> sub-district -> village chain. */
interface GeoChain {
  state: AdministrativeUnit;
  district: AdministrativeUnit;
  subDistrict: AdministrativeUnit;
  village: AdministrativeUnit;
}

/**
 * Walks the ingested hierarchy deterministically (ascending LGD code order)
 * and returns up to `wanted` chains, each from a different state where the
 * data allows. Probe counts are bounded so a large hierarchy cannot turn this
 * into an unbounded number of requests.
 */
async function resolveGeoChains(wanted: number, maxProbes = 400): Promise<GeoChain[]> {
  const states = [...(await getStates())].sort(byCode);
  const chains: GeoChain[] = [];
  const usedStates = new Set<string>();
  let probes = 0;

  for (const state of states) {
    if (chains.length >= wanted) break;

    // Prefer an unused state, but allow reuse once every state is exhausted.
    if (usedStates.has(state.code) && chains.length > 0) continue;

    const districts = [...(await getDistricts(state.code))].sort(byCode);
    for (const district of districts) {
      if (chains.length >= wanted || probes >= maxProbes) break;
      if (usedStates.has(state.code) && chains.length > 0) break;

      const subDistricts = [...(await getSubDistricts(district.code))].sort(byCode);
      for (const subDistrict of subDistricts) {
        if (chains.length >= wanted || probes >= maxProbes) break;
        probes++;

        const { villages } = await getVillages(subDistrict.code, { page: 1, limit: 5 });
        const village = [...villages].sort(byCode)[0];
        if (!village) continue;

        chains.push({ state, district, subDistrict, village });
        usedStates.add(state.code);
        break;
      }
    }
  }
  return chains;
}

async function seedWorkflows(): Promise<{ rfctlarrId: string }> {
  console.log('1. Seeding workflows...');
  const { data: existingWf } = await supabase.from('workflows').select('id, code');

  const defs = [
    {
      code: 'RFCTLARR_2013',
      name: 'RFCTLARR Act 2013 Standard Acquisition',
      description:
        'Statutory land acquisition under the Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013.',
      legal_framework: 'RFCTLARR Act 2013',
      version: '1.0',
    },
    {
      code: 'DIRECT_PURCHASE',
      name: 'Direct Land Purchase & Consent Model',
      description:
        'Expedited acquisition via mutual agreement with landowners with direct compensation settlement.',
      legal_framework: 'State Direct Purchase Policy',
      version: '1.0',
    },
  ];

  let rfctlarrId = '';
  for (const d of defs) {
    const found = existingWf?.find((w) => w.code === d.code);
    if (found) {
      if (d.code === 'RFCTLARR_2013') rfctlarrId = found.id;
      continue;
    }
    const { data, error } = await supabase.from('workflows').insert(d).select('*').single();
    if (error) throw error;
    if (d.code === 'RFCTLARR_2013') rfctlarrId = data.id;
  }
  return { rfctlarrId };
}

async function seedStages(rfctlarrId: string): Promise<Map<string, string>> {
  console.log('2. Seeding RFCTLARR 2013 stage definitions...');
  const { data: existingStages } = await supabase
    .from('workflow_stages')
    .select('id, code')
    .eq('workflow_id', rfctlarrId);

  const stageIdMap = new Map<string, string>();
  if (existingStages && existingStages.length > 0) {
    existingStages.forEach((s) => stageIdMap.set(s.code, s.id));
    return stageIdMap;
  }

  const stageDefs = [
    {
      stage_number: 1,
      code: 'SEC_11_NOTIFICATION',
      title: 'Preliminary Notification (Section 11)',
      description:
        'Publication of preliminary notification in official gazette, newspapers, and panchayat/village offices.',
      default_duration_days: 30,
      is_mandatory: true,
      required_role: 'lao',
      required_documents: ['preliminary_notice', 'survey_report'],
      completion_criteria: { requires_all_documents: true },
    },
    {
      stage_number: 2,
      code: 'SEC_15_HEARING',
      title: 'Objection Hearing & Verification (Section 15)',
      description:
        '60-day statutory window for receiving objections, holding hearings, and submitting report to Collector.',
      default_duration_days: 60,
      is_mandatory: true,
      required_role: 'lao',
      required_documents: ['hearing_minutes'],
      completion_criteria: { requires_approval: true },
    },
    {
      stage_number: 3,
      code: 'SEC_19_DECLARATION',
      title: 'Declaration of Acquisition (Section 19)',
      description:
        'Formal declaration published by appropriate government after reviewing the Section 15 report.',
      default_duration_days: 30,
      is_mandatory: true,
      required_role: 'approver',
      required_documents: ['sec_19_declaration'],
      completion_criteria: { requires_approval: true },
    },
    {
      stage_number: 4,
      code: 'SEC_26_VALUATION',
      title: 'Land Measurement & Valuation (Section 26-29)',
      description:
        'Joint measurement survey, market value determination, and solatium calculation.',
      default_duration_days: 45,
      is_mandatory: true,
      required_role: 'revenue_inspector',
      required_documents: ['valuation_record', 'survey_report'],
      completion_criteria: { requires_survey_verified: true },
    },
    {
      stage_number: 5,
      code: 'SEC_30_AWARD',
      title: 'Determination of Award (Section 30)',
      description: 'Formal award enquiry and pronouncement of compensation award by the Collector.',
      default_duration_days: 30,
      is_mandatory: true,
      required_role: 'lao',
      required_documents: ['award_order'],
      completion_criteria: { requires_approval: true },
    },
    {
      stage_number: 6,
      code: 'SEC_37_COMPENSATION',
      title: 'Compensation Disbursement (Section 37)',
      description:
        'Direct benefit transfer or deposit of compensation into landowners verified bank accounts.',
      default_duration_days: 45,
      is_mandatory: true,
      required_role: 'revenue_inspector',
      required_documents: ['disbursement_slips'],
      completion_criteria: {},
    },
    {
      stage_number: 7,
      code: 'SEC_38_POSSESSION',
      title: 'Physical Possession & Handover (Section 38)',
      description:
        'Taking physical possession of land and execution of possession memo to project authority.',
      default_duration_days: 30,
      is_mandatory: true,
      required_role: 'lao',
      required_documents: ['possession_memo'],
      completion_criteria: { requires_approval: true },
    },
  ];

  for (const s of stageDefs) {
    const { data, error } = await supabase
      .from('workflow_stages')
      .insert({ ...s, workflow_id: rfctlarrId })
      .select('id, code')
      .single();
    if (error) throw error;
    stageIdMap.set(data.code, data.id);
  }

  console.log('   Linking sequential stage dependencies...');
  const codes = stageDefs.map((s) => s.code);
  for (let i = 1; i < codes.length; i++) {
    const { error } = await supabase.from('stage_dependencies').insert({
      stage_id: stageIdMap.get(codes[i])!,
      depends_on_stage_id: stageIdMap.get(codes[i - 1])!,
      dependency_type: 'finish_to_start',
      lag_days: 0,
    });
    if (error && !String(error.message).toLowerCase().includes('duplicate')) throw error;
  }
  return stageIdMap;
}

async function seedProjectsAndCases(
  rfctlarrId: string,
  chains: GeoChain[]
): Promise<void> {
  const { data: existingProjects } = await supabase.from('projects').select('id, code');

  // Project definitions carry NO geography: each one is bound to a chain that
  // was resolved from the database a moment ago.
  const projectDefs = [
    {
      code: 'DEMO-PRJ-01',
      name: `${DEMO_LABEL} — Industrial Corridor Logistics Node`,
      description: `${DEMO_NOTE} Multi-modal logistics hub and industrial corridor package.`,
      project_type: 'industrial',
      sponsoring_agency: 'Demonstration sponsoring agency (sample data)',
      estimated_budget: 850000000,
      target_completion_date: '2027-12-31',
      status: 'in_progress',
    },
    {
      code: 'DEMO-PRJ-02',
      name: `${DEMO_LABEL} — Dedicated Freight Corridor Package`,
      description: `${DEMO_NOTE} Electrified double-track freight railway corridor alignment.`,
      project_type: 'railway',
      sponsoring_agency: 'Demonstration sponsoring agency (sample data)',
      estimated_budget: 1200000000,
      target_completion_date: '2028-06-30',
      status: 'in_progress',
    },
    {
      code: 'DEMO-PRJ-03',
      name: `${DEMO_LABEL} — Highway Bypass Widening`,
      description: `${DEMO_NOTE} Bypass expansion to alleviate arterial traffic congestion.`,
      project_type: 'highway',
      sponsoring_agency: 'Demonstration sponsoring agency (sample data)',
      estimated_budget: 450000000,
      target_completion_date: '2026-11-30',
      status: 'in_progress',
    },
  ];

  const projectIds: string[] = [];
  for (const p of projectDefs) {
    const found = existingProjects?.find((ep) => ep.code === p.code);
    if (found) {
      projectIds.push(found.id);
      continue;
    }
    const { data, error } = await supabase.from('projects').insert(p).select('*').single();
    if (error) throw error;
    projectIds.push(data.id);
  }

  const { data: existingCases } = await supabase
    .from('acquisition_cases')
    .select('id, case_number');

  for (let idx = 0; idx < chains.length && idx < 3; idx++) {
    const chain = chains[idx];
    const projectId = projectIds[idx % projectIds.length];

    const caseNumber = `DEMO-${chain.state.code}-${chain.district.code}-2026-${100 + idx}`;

    if (existingCases?.some((ec) => ec.case_number === caseNumber)) continue;

    const { data: newCase, error: caseErr } = await supabase
      .from('acquisition_cases')
      .insert({
        case_number: caseNumber,
        project_id: projectId,
        workflow_id: rfctlarrId,
        title: `${DEMO_LABEL} — acquisition case ${caseNumber}`,
        description: `${DEMO_NOTE} Located in ${chain.village.name}, ${chain.subDistrict.name} sub-district, ${chain.district.name} district, ${chain.state.name}.`,
        state: chain.state.name,
        district: chain.district.name,
        tehsil: chain.subDistrict.name,
        village: chain.village.name,
        state_lgd_code: chain.state.code,
        district_lgd_code: chain.district.code,
        subdistrict_lgd_code: chain.subDistrict.code,
        village_lgd_code: chain.village.code,
        total_area_hectares: 34.5,
        estimated_compensation: 145000000,
        status: idx === 0 ? 'delayed' : 'active',
        priority: idx === 0 ? 'high' : 'medium',
        start_date: '2026-03-01',
        expected_completion_date: '2026-12-15',
      })
      .select('*')
      .single();
    if (caseErr) throw caseErr;

    // Deterministic parcel identifiers — no Math.random(), so a re-run and a
    // fresh database always produce the same rows.
    const parcelSeed = 101 + idx * 10;
    const { error: parcelErr } = await supabase.from('parcels').insert([
      {
        case_id: newCase.id,
        survey_number: `SY-${parcelSeed}/1`,
        khata_number: `KH-${20 + idx}`,
        landowner_names: [`Demonstration landowner ${parcelSeed}A (sample record)`],
        land_type: 'Agricultural Irrigated',
        area_acres: 4.25,
        compensation_amount: 18500000,
        acquisition_status: 'notified',
      },
      {
        case_id: newCase.id,
        survey_number: `SY-${parcelSeed}/2`,
        khata_number: `KH-${21 + idx}`,
        landowner_names: [`Demonstration landowner ${parcelSeed}B (sample record)`],
        land_type: 'Agricultural Fallow',
        area_acres: 6.8,
        compensation_amount: 24000000,
        acquisition_status: 'identified',
      },
    ]);
    if (parcelErr) throw parcelErr;

    const { stageInstances, expectedCompletionDate } = await initializeCaseWorkflow(
      newCase.id,
      rfctlarrId,
      newCase.start_date
    );

    await supabase
      .from('acquisition_cases')
      .update({ expected_completion_date: expectedCompletionDate })
      .eq('id', newCase.id);

    // Demonstrate real stage progression through the real engine.
    if (idx === 0 && stageInstances.length >= 4) {
      await advanceStageInstance({
        caseId: newCase.id,
        stageInstanceId: stageInstances[0].id,
        targetStatus: 'completed',
        actualDate: '2026-03-25',
        notes: `${DEMO_LABEL}: preliminary notification gazetted (sample record).`,
        actorName: DEMO_ACTOR,
      });
      await advanceStageInstance({
        caseId: newCase.id,
        stageInstanceId: stageInstances[1].id,
        targetStatus: 'completed',
        actualDate: '2026-05-20',
        notes: `${DEMO_LABEL}: objection hearing completed (sample record).`,
        actorName: DEMO_ACTOR,
      });
      await advanceStageInstance({
        caseId: newCase.id,
        stageInstanceId: stageInstances[2].id,
        targetStatus: 'completed',
        actualDate: '2026-06-18',
        notes: `${DEMO_LABEL}: declaration approved and published (sample record).`,
        actorName: DEMO_ACTOR,
      });
    }

    await supabase.from('case_events').insert({
      case_id: newCase.id,
      event_type: 'CASE_CREATED',
      title: `Demonstration case ${caseNumber} registered`,
      description: `${DEMO_NOTE} Registered with ${newCase.total_area_hectares} hectares under ${chain.state.name} administration.`,
      actor_name: DEMO_ACTOR,
      metadata: {
        record_kind: 'demonstration',
        sample: true,
        seeded_by: 'scripts/seed.ts',
        geography_source: 'administrative_units',
        lgd_codes: {
          state: chain.state.code,
          district: chain.district.code,
          subdistrict: chain.subDistrict.code,
          village: chain.village.code,
        },
      },
    });

    console.log(
      `   seeded ${caseNumber} in ${chain.village.name} (${chain.district.name}, ${chain.state.name}) ` +
        `LGD ${chain.state.code}/${chain.district.code}/${chain.subDistrict.code}/${chain.village.code}`
    );
  }
}

async function seed() {
  console.log('BhoomiSetu demonstration seed');

  const { rfctlarrId } = await seedWorkflows();
  await seedStages(rfctlarrId);

  console.log('3. Resolving administrative geography from the database...');
  const provenance = await getGeographyProvenance();
  console.log(`   source status: ${provenance.status} | units in database: ${provenance.units_in_database}`);

  const chains = await resolveGeoChains(3);

  if (chains.length === 0) {
    console.log('\nSKIPPED: no demonstration projects or cases were created.');
    console.log(
      '  acquisition_cases.state / district / village are NOT NULL, and this script will not\n' +
        '  invent geography to satisfy them. The administrative hierarchy has not been ingested\n' +
        `  (${provenance.status}; ${provenance.units_in_database} units in the database).`
    );
    if (provenance.requires) console.log(`  Required: ${provenance.requires}`);
    console.log(
      '  Workflow definitions and stage dependencies were created above and are reusable.\n' +
        '  Re-run this script after the administrative geography hierarchy is ingested.\n'
    );
    return;
  }

  console.log(`   resolved ${chains.length} state -> district -> sub-district -> village chain(s)`);

  console.log('4. Seeding labelled demonstration projects and cases...');
  await seedProjectsAndCases(rfctlarrId, chains);

  console.log('\nSeed completed.');
  console.log(
    'All projects, cases, parcels, stage instances and audit events above are labelled\n' +
      'demonstration records stored in the database and produced by the real workflow engine.'
  );
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
