/**
 * BhoomiSetu - Authoritative Data-Driven ISRO Bhuvan Layer Catalogue & Resolver
 * 
 * Strict Architectural Principles:
 * 1. ZERO HARDCODING: No application conditionals like `if (state === "Bihar")`.
 * 2. FULL ALL-INDIA COVERAGE: Data-driven mapping across all Indian States & Union Territories.
 * 3. NO FABRICATION: If Bhuvan does not expose a verified layer for a jurisdiction,
 *    honestly report `unavailable` / `not_available_for_jurisdiction`.
 * 4. STRICT ATTRIBUTION: All layers mandate "ISRO / NRSC Bhuvan" attribution.
 * 5. NON-CADASTRAL DISCLAIMER: Explicit statutory disclosure that thematic rasters are for
 *    planning/development and not cadastral ground truth.
 * 6. VERIFICATION METADATA: Every active layer is backed by live GetCapabilities & GetMap proof.
 */

export type BhuvanWorkspace = 'lulc' | 'disaster' | 'admin' | 'vector' | 'moef' | 'pmgsy';

export interface BhuvanLayerEntry {
  layer_id: string;
  provider: 'bhuvan';
  workspace: BhuvanWorkspace;
  layer_name: string; // OGC layer parameter e.g. "lulc:MH_LULC50K_1516"
  title: string;
  layer_type: 'wms_raster';
  coverage: 'national' | 'state' | 'regional';
  state_code?: string; // 2-letter ISO 3166-2:IN subcode
  state_name?: string; // Canonical state name
  lgd_state_code?: number; // Ministry of Panchayati Raj LGD state code
  temporal_reference: string; // e.g. "2015–16", "2011–12", "2023"
  freshness_class: 'reference' | 'historical' | 'static';
  purpose: string;
  supported_crs: string[];
  enabled: boolean;
  verification_status: 'verified' | 'unverified' | 'unavailable';
  capabilities_verified: boolean;
  getmap_verified: boolean;
  last_verified_at: string;
  attribution: string;
  usage_notes: string;
  analytical_classification: 'supporting_spatial_context' | 'visualization';
  default_opacity: number;
}

export interface BhuvanLayerContext {
  state_codes?: string[];
  state_names?: string[];
  bbox?: [number, number, number, number];
  workspace?: BhuvanWorkspace;
}

export interface BhuvanResolvedLayer {
  layer: BhuvanLayerEntry;
  wms_url: string;
  applicable_jurisdiction?: string;
  status: 'available' | 'unavailable' | 'not_available_for_jurisdiction';
  reason?: string;
}

export interface BhuvanResolutionResult {
  resolved_layers: BhuvanResolvedLayer[];
  unsupported_jurisdictions: string[];
  total_resolved: number;
  timestamp: string;
}

/**
 * Standard Indian Administrative Geography Reference Dictionary
 * Used strictly for bidirectional normalization between state names and ISO/LGD codes.
 */
export const INDIAN_STATES_REFERENCE: ReadonlyArray<{
  code: string;
  name: string;
  aliases: string[];
  lgd_code?: number;
}> = [
  { code: 'AN', name: 'Andaman and Nicobar Islands', aliases: ['andaman & nicobar', 'andaman and nicobar', 'andaman', 'a&n'], lgd_code: 35 },
  { code: 'AP', name: 'Andhra Pradesh', aliases: ['andhra pradesh', 'andhra', 'ap'], lgd_code: 28 },
  { code: 'AR', name: 'Arunachal Pradesh', aliases: ['arunachal pradesh', 'arunachal', 'ar'], lgd_code: 12 },
  { code: 'AS', name: 'Assam', aliases: ['assam', 'as'], lgd_code: 18 },
  { code: 'BR', name: 'Bihar', aliases: ['bihar', 'br'], lgd_code: 10 },
  { code: 'CH', name: 'Chandigarh', aliases: ['chandigarh', 'ch'], lgd_code: 4 },
  { code: 'CG', name: 'Chhattisgarh', aliases: ['chhattisgarh', 'chattisgarh', 'cg', 'ct'], lgd_code: 22 },
  { code: 'DD', name: 'Daman and Diu', aliases: ['daman and diu', 'daman & diu', 'daman', 'diu', 'dd'], lgd_code: 25 },
  { code: 'DN', name: 'Dadra and Nagar Haveli', aliases: ['dadra and nagar haveli', 'dadra & nagar haveli', 'dnh', 'dn'], lgd_code: 26 },
  { code: 'DL', name: 'Delhi', aliases: ['delhi', 'nct of delhi', 'national capital territory of delhi', 'dl'], lgd_code: 7 },
  { code: 'GA', name: 'Goa', aliases: ['goa', 'ga'], lgd_code: 30 },
  { code: 'GJ', name: 'Gujarat', aliases: ['gujarat', 'gj'], lgd_code: 24 },
  { code: 'HR', name: 'Haryana', aliases: ['haryana', 'hr'], lgd_code: 6 },
  { code: 'HP', name: 'Himachal Pradesh', aliases: ['himachal pradesh', 'himachal', 'hp'], lgd_code: 2 },
  { code: 'JK', name: 'Jammu and Kashmir', aliases: ['jammu and kashmir', 'jammu & kashmir', 'j&k', 'jk'], lgd_code: 1 },
  { code: 'JH', name: 'Jharkhand', aliases: ['jharkhand', 'jh'], lgd_code: 20 },
  { code: 'KA', name: 'Karnataka', aliases: ['karnataka', 'ka'], lgd_code: 29 },
  { code: 'KL', name: 'Kerala', aliases: ['kerala', 'kl'], lgd_code: 32 },
  { code: 'LA', name: 'Ladakh', aliases: ['ladakh', 'la'], lgd_code: 37 },
  { code: 'LD', name: 'Lakshadweep', aliases: ['lakshadweep', 'ld'], lgd_code: 31 },
  { code: 'MP', name: 'Madhya Pradesh', aliases: ['madhya pradesh', 'mp'], lgd_code: 23 },
  { code: 'MH', name: 'Maharashtra', aliases: ['maharashtra', 'mh'], lgd_code: 27 },
  { code: 'MN', name: 'Manipur', aliases: ['manipur', 'mn'], lgd_code: 14 },
  { code: 'ML', name: 'Meghalaya', aliases: ['meghalaya', 'ml'], lgd_code: 17 },
  { code: 'MZ', name: 'Mizoram', aliases: ['mizoram', 'mz'], lgd_code: 15 },
  { code: 'NL', name: 'Nagaland', aliases: ['nagaland', 'nl'], lgd_code: 13 },
  { code: 'OD', name: 'Odisha', aliases: ['odisha', 'orissa', 'od', 'or'], lgd_code: 21 },
  { code: 'PB', name: 'Punjab', aliases: ['punjab', 'pb'], lgd_code: 3 },
  { code: 'PY', name: 'Puducherry', aliases: ['puducherry', 'pondicherry', 'py'], lgd_code: 34 },
  { code: 'RJ', name: 'Rajasthan', aliases: ['rajasthan', 'rj'], lgd_code: 8 },
  { code: 'SK', name: 'Sikkim', aliases: ['sikkim', 'sk'], lgd_code: 11 },
  { code: 'TN', name: 'Tamil Nadu', aliases: ['tamil nadu', 'tamilnadu', 'tn'], lgd_code: 33 },
  { code: 'TS', name: 'Telangana', aliases: ['telangana', 'ts', 'tg'], lgd_code: 36 },
  { code: 'TR', name: 'Tripura', aliases: ['tripura', 'tr'], lgd_code: 16 },
  { code: 'UP', name: 'Uttar Pradesh', aliases: ['uttar pradesh', 'up'], lgd_code: 9 },
  { code: 'UK', name: 'Uttarakhand', aliases: ['uttarakhand', 'uttaranchal', 'uk', 'ua'], lgd_code: 5 },
  { code: 'WB', name: 'West Bengal', aliases: ['west bengal', 'bengal', 'wb'], lgd_code: 19 },
];

/**
 * Normalizes any freeform state name, alias, or code to official 2-letter code.
 */
export function normalizeJurisdictionToStateCode(input?: string | null): string | null {
  if (!input || typeof input !== 'string') return null;
  const clean = input.trim().toLowerCase();
  if (clean.length === 0) return null;

  // Direct code match
  const directMatch = INDIAN_STATES_REFERENCE.find(s => s.code.toLowerCase() === clean);
  if (directMatch) return directMatch.code;

  // Name or alias match
  const aliasMatch = INDIAN_STATES_REFERENCE.find(s => 
    s.name.toLowerCase() === clean || s.aliases.some(a => a.toLowerCase() === clean)
  );
  if (aliasMatch) return aliasMatch.code;

  return null;
}

/**
 * Verified Bhuvan Base Service Endpoints
 */
export const BHUVAN_WMS_ROOT = 'https://bhuvan-vec2.nrsc.gov.in/bhuvan/wms';
export const BHUVAN_LULC_WMS_ENDPOINT = 'https://bhuvan-vec2.nrsc.gov.in/bhuvan/lulc/wms';
export const BHUVAN_DISASTER_WMS_ENDPOINT = 'https://bhuvan-vec2.nrsc.gov.in/bhuvan/disaster/wms';
export const BHUVAN_ATTRIBUTION = 'ISRO / NRSC Bhuvan';
export const BHUVAN_STATUTORY_DISCLAIMER =
  'Thematic reference spatial data. Not cadastral ground truth. Intended for planning and development purposes only.';

/**
 * Authoritative Verified Bhuvan Layer Catalogue
 * Built strictly from verified NRSC capabilities on bhuvan-vec2.
 */
export const BHUVAN_LAYER_CATALOGUE: ReadonlyArray<BhuvanLayerEntry> = [
  {
    layer_id: 'bhuvan_lulc_50k_an_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:AN_LULC50K_1516',
    title: 'Andaman and Nicobar Islands Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'AN',
    state_name: 'Andaman and Nicobar Islands',
    lgd_state_code: 35,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ap_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:AP_LULC50K_1516',
    title: 'Andhra Pradesh Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'AP',
    state_name: 'Andhra Pradesh',
    lgd_state_code: 28,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ar_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:AR_LULC50K_1516',
    title: 'Arunachal Pradesh Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'AR',
    state_name: 'Arunachal Pradesh',
    lgd_state_code: 12,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_as_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:AS_LULC50K_1516',
    title: 'Assam Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'AS',
    state_name: 'Assam',
    lgd_state_code: 18,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_br_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:BR_LULC50K_1516',
    title: 'Bihar Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'BR',
    state_name: 'Bihar',
    lgd_state_code: 10,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ch_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:CH_LULC50K_1516',
    title: 'Chandigarh Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'CH',
    state_name: 'Chandigarh',
    lgd_state_code: 4,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_cg_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:CG_LULC50K_1516',
    title: 'Chhattisgarh Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'CG',
    state_name: 'Chhattisgarh',
    lgd_state_code: 22,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_dd_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:DD_LULC50K_1516',
    title: 'Daman and Diu Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'DD',
    state_name: 'Daman and Diu',
    lgd_state_code: 25,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_dn_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:DN_LULC50K_1516',
    title: 'Dadra and Nagar Haveli Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'DN',
    state_name: 'Dadra and Nagar Haveli',
    lgd_state_code: 26,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_dl_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:DL_LULC50K_1516',
    title: 'Delhi Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'DL',
    state_name: 'Delhi',
    lgd_state_code: 7,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ga_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:GA_LULC50K_1516',
    title: 'Goa Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'GA',
    state_name: 'Goa',
    lgd_state_code: 30,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_gj_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:GJ_LULC50K_1516',
    title: 'Gujarat Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'GJ',
    state_name: 'Gujarat',
    lgd_state_code: 24,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_hr_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:HR_LULC50K_1516',
    title: 'Haryana Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'HR',
    state_name: 'Haryana',
    lgd_state_code: 6,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_hp_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:HP_LULC50K_1516',
    title: 'Himachal Pradesh Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'HP',
    state_name: 'Himachal Pradesh',
    lgd_state_code: 2,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_jk_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:JK_LULC50K_1516',
    title: 'Jammu and Kashmir Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'JK',
    state_name: 'Jammu and Kashmir',
    lgd_state_code: 1,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_jh_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:JH_LULC50K_1516',
    title: 'Jharkhand Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'JH',
    state_name: 'Jharkhand',
    lgd_state_code: 20,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ka_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:KA_LULC50K_1516',
    title: 'Karnataka Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'KA',
    state_name: 'Karnataka',
    lgd_state_code: 29,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_kl_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:KL_LULC50K_1516',
    title: 'Kerala Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'KL',
    state_name: 'Kerala',
    lgd_state_code: 32,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ld_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:LD_LULC50K_1516',
    title: 'Lakshadweep Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'LD',
    state_name: 'Lakshadweep',
    lgd_state_code: 31,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_mp_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:MP_LULC50K_1516',
    title: 'Madhya Pradesh Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'MP',
    state_name: 'Madhya Pradesh',
    lgd_state_code: 23,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_mh_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:MH_LULC50K_1516',
    title: 'Maharashtra Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'MH',
    state_name: 'Maharashtra',
    lgd_state_code: 27,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_mn_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:MN_LULC50K_1516',
    title: 'Manipur Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'MN',
    state_name: 'Manipur',
    lgd_state_code: 14,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ml_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:ML_LULC50K_1516',
    title: 'Meghalaya Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'ML',
    state_name: 'Meghalaya',
    lgd_state_code: 17,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_mz_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:MZ_LULC50K_1516',
    title: 'Mizoram Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'MZ',
    state_name: 'Mizoram',
    lgd_state_code: 15,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_nl_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:NL_LULC50K_1516',
    title: 'Nagaland Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'NL',
    state_name: 'Nagaland',
    lgd_state_code: 13,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_od_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:OD_LULC50K_1516',
    title: 'Odisha Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'OD',
    state_name: 'Odisha',
    lgd_state_code: 21,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_pb_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:PB_LULC50K_1516',
    title: 'Punjab Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'PB',
    state_name: 'Punjab',
    lgd_state_code: 3,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_py_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:PY_LULC50K_1516',
    title: 'Puducherry Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'PY',
    state_name: 'Puducherry',
    lgd_state_code: 34,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_rj_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:RJ_LULC50K_1516',
    title: 'Rajasthan Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'RJ',
    state_name: 'Rajasthan',
    lgd_state_code: 8,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_sk_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:SK_LULC50K_1516',
    title: 'Sikkim Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'SK',
    state_name: 'Sikkim',
    lgd_state_code: 11,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_tn_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:TN_LULC50K_1516',
    title: 'Tamil Nadu Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'TN',
    state_name: 'Tamil Nadu',
    lgd_state_code: 33,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_ts_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:TS_LULC50K_1516',
    title: 'Telangana Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'TS',
    state_name: 'Telangana',
    lgd_state_code: 36,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_tr_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:TR_LULC50K_1516',
    title: 'Tripura Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'TR',
    state_name: 'Tripura',
    lgd_state_code: 16,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_up_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:UP_LULC50K_1516',
    title: 'Uttar Pradesh Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'UP',
    state_name: 'Uttar Pradesh',
    lgd_state_code: 9,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_uk_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:UK_LULC50K_1516',
    title: 'Uttarakhand Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'UK',
    state_name: 'Uttarakhand',
    lgd_state_code: 5,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_lulc_50k_wb_1516',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:WB_LULC50K_1516',
    title: 'West Bengal Land Use / Land Cover (LULC 50K - 2015-16)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'WB',
    state_name: 'West Bengal',
    lgd_state_code: 19,
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Thematic land classification at 1:50,000 scale.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 via GetCapabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  // --------------------------------------------------------------------------
  // HONEST UNAVAILABLE STATE ENTRY: LADAKH (No 2015-16 LULC cycle layer published)
  // --------------------------------------------------------------------------
  {
    layer_id: 'bhuvan_lulc_50k_la_unavailable',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:LA_LULC50K_1516',
    title: 'Ladakh Land Use / Land Cover (LULC 50K - Not Published / Unavailable)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'LA',
    state_name: 'Ladakh',
    lgd_state_code: 37,
    temporal_reference: 'Unavailable',
    freshness_class: 'historical',
    purpose: 'Administrative placeholder representing lack of Bhuvan state-level layer.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: false,
    verification_status: 'unavailable',
    capabilities_verified: false,
    getmap_verified: false,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Bhuvan does not publish a standalone LA_LULC50K_1516 layer (Ladakh formed in 2019). Honestly marked unavailable.',
    analytical_classification: 'visualization',
    default_opacity: 0,
  },
  {
    layer_id: 'bhuvan_disaster_ls_ar_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_ARUNACHAL_2023',
    title: 'Arunachal Pradesh Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'AR',
    state_name: 'Arunachal Pradesh',
    lgd_state_code: 12,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_as_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_ASSAM_2023',
    title: 'Assam Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'AS',
    state_name: 'Assam',
    lgd_state_code: 18,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_ga_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_GOA_2023',
    title: 'Goa Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'GA',
    state_name: 'Goa',
    lgd_state_code: 30,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_hp_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_HIMACHALPRADESH_2023',
    title: 'Himachal Pradesh Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'HP',
    state_name: 'Himachal Pradesh',
    lgd_state_code: 2,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_jk_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_J%26K_2023',
    title: 'Jammu and Kashmir Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'JK',
    state_name: 'Jammu and Kashmir',
    lgd_state_code: 1,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_kl_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_KERELA_2023',
    title: 'Kerala Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'KL',
    state_name: 'Kerala',
    lgd_state_code: 32,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_mh_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_MAHARASHTRA_2023',
    title: 'Maharashtra Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'MH',
    state_name: 'Maharashtra',
    lgd_state_code: 27,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_ml_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_MEGHALAYA_2023',
    title: 'Meghalaya Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'ML',
    state_name: 'Meghalaya',
    lgd_state_code: 17,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_mz_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_MIZORAM_2023',
    title: 'Mizoram Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'MZ',
    state_name: 'Mizoram',
    lgd_state_code: 15,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_nl_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_NAGALAND_2023',
    title: 'Nagaland Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'NL',
    state_name: 'Nagaland',
    lgd_state_code: 13,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_sk_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_SIKKIM_2023',
    title: 'Sikkim Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'SK',
    state_name: 'Sikkim',
    lgd_state_code: 11,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_tn_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_TAMILNADU_2023',
    title: 'Tamil Nadu Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'TN',
    state_name: 'Tamil Nadu',
    lgd_state_code: 33,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_tr_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_TRIPURA_2023',
    title: 'Tripura Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'TR',
    state_name: 'Tripura',
    lgd_state_code: 16,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_uk_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_UTTARAKHAND_2023',
    title: 'Uttarakhand Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'UK',
    state_name: 'Uttarakhand',
    lgd_state_code: 5,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  {
    layer_id: 'bhuvan_disaster_ls_wb_2023',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'disaster:LS_WESTBENGAL_2023',
    title: 'West Bengal Landslide Susceptibility & Hazard (2023)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'WB',
    state_name: 'West Bengal',
    lgd_state_code: 19,
    temporal_reference: '2023',
    freshness_class: 'reference',
    purpose: 'Landslide hazard susceptibility overlay for infrastructure corridor planning.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 disaster capabilities and GetMap PNG raster request.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.6,
  },
  // --------------------------------------------------------------------------
  // 3. VERIFIED REGIONAL THEMATIC & BOUNDARY LAYERS
  // --------------------------------------------------------------------------
  {
    layer_id: 'bhuvan_lulc_ganga_basin',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:GANGA_LULC',
    title: 'Ganga River Basin Land Use / Land Cover Cartography',
    layer_type: 'wms_raster',
    coverage: 'regional',
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'Regional river basin environmental and land classification.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live on bhuvan-vec2 lulc workspace. Basin-level cross-border coverage.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.65,
  },
  {
    layer_id: 'bhuvan_admin_ap_tg_bnd',
    provider: 'bhuvan',
    workspace: 'admin',
    layer_name: 'admin:AP_Telengana_bnd_line',
    title: 'Andhra Pradesh - Telangana Reorganization Boundary Line',
    layer_type: 'wms_raster',
    coverage: 'regional',
    temporal_reference: '2014',
    freshness_class: 'static',
    purpose: 'Interstate boundary alignment context for bifurcation corridor disputes.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: true,
    verification_status: 'verified',
    capabilities_verified: true,
    getmap_verified: true,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Verified live in bhuvan-vec2 admin capabilities and GetMap PNG tile.',
    analytical_classification: 'supporting_spatial_context',
    default_opacity: 0.75,
  },
  // --------------------------------------------------------------------------
  // 4. INVALID / DEPRECATED PLACEHOLDERS EXPLICITLY DISABLED
  // (Maintained strictly for auditability and prevention of silent regression)
  // --------------------------------------------------------------------------
  {
    layer_id: 'bhuvan_lulc_builtup_national_disabled',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:LULC_BUILTUP',
    title: 'National Built-Up Land (Disabled - GetMap returns LayerNotDefined)',
    layer_type: 'wms_raster',
    coverage: 'national',
    temporal_reference: '2015–16',
    freshness_class: 'reference',
    purpose: 'National built-up infrastructure and human settlement demarcation.',
    supported_crs: ['EPSG:4326', 'EPSG:3857'],
    enabled: false,
    verification_status: 'unavailable',
    capabilities_verified: true,
    getmap_verified: false,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Advertised in capabilities XML but fails GetMap raster with LayerNotDefined. Disabled.',
    analytical_classification: 'visualization',
    default_opacity: 0,
  },
  {
    layer_id: 'bhuvan_wasteland_50k_legacy',
    provider: 'bhuvan',
    workspace: 'lulc',
    layer_name: 'lulc:BR_WL50K_0506',
    title: 'Bhuvan Wasteland Delineation 50K (Legacy Placeholder - Unavailable)',
    layer_type: 'wms_raster',
    coverage: 'state',
    state_code: 'BR',
    temporal_reference: '2005–06',
    freshness_class: 'historical',
    purpose: 'Legacy placeholder',
    supported_crs: ['EPSG:4326'],
    enabled: false,
    verification_status: 'unavailable',
    capabilities_verified: false,
    getmap_verified: false,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Audited & removed: Returns OGC LayerNotDefined on bhuvan-vec2.',
    analytical_classification: 'visualization',
    default_opacity: 0,
  },
  {
    layer_id: 'bhuvan_flood_hazard_legacy',
    provider: 'bhuvan',
    workspace: 'disaster',
    layer_name: 'flood:hazard_layer',
    title: 'Bhuvan Flood Hazard Layer (Legacy Placeholder - Unavailable)',
    layer_type: 'wms_raster',
    coverage: 'national',
    temporal_reference: 'Historical',
    freshness_class: 'historical',
    purpose: 'Legacy placeholder',
    supported_crs: ['EPSG:4326'],
    enabled: false,
    verification_status: 'unavailable',
    capabilities_verified: false,
    getmap_verified: false,
    last_verified_at: '2026-09-24T22:25:00.000Z',
    attribution: BHUVAN_ATTRIBUTION,
    usage_notes: 'Audited & removed: Invalid workspace "flood" and placeholder layer name.',
    analytical_classification: 'visualization',
    default_opacity: 0,
  },
];

/**
 * Data-Driven Layer Resolver
 * Resolves verified Bhuvan WMS layers for given state codes, names, or bounding box.
 * Strictly ZERO hardcoding: matching is purely relational based on catalog attributes.
 */
export function resolveBhuvanLayers(context: BhuvanLayerContext = {}): BhuvanResolutionResult {
  const targetStateCodes = new Set<string>();

  // 1. Gather state codes from explicit codes
  if (context.state_codes && Array.isArray(context.state_codes)) {
    for (const code of context.state_codes) {
      const normalized = normalizeJurisdictionToStateCode(code);
      if (normalized) targetStateCodes.add(normalized);
    }
  }

  // 2. Gather state codes from state names
  if (context.state_names && Array.isArray(context.state_names)) {
    for (const name of context.state_names) {
      const normalized = normalizeJurisdictionToStateCode(name);
      if (normalized) targetStateCodes.add(normalized);
    }
  }

  const resolvedLayers: BhuvanResolvedLayer[] = [];
  const unsupportedJurisdictions: string[] = [];

  // Filter catalogue strictly by enabled and verified entries
  const activeCatalogue = BHUVAN_LAYER_CATALOGUE.filter(
    l => l.enabled && l.verification_status === 'verified'
  );

  // If workspace filter is provided
  const scopedCatalogue = context.workspace
    ? activeCatalogue.filter(l => l.workspace === context.workspace)
    : activeCatalogue;

  // Case A: Jurisdictions specified (single or multi-state corridor)
  if (targetStateCodes.size > 0) {
    for (const stateCode of targetStateCodes) {
      const stateLayers = scopedCatalogue.filter(l => l.state_code === stateCode);

      if (stateLayers.length === 0) {
        // Record honest missing coverage
        const stateRef = INDIAN_STATES_REFERENCE.find(s => s.code === stateCode);
        const displayName = stateRef ? stateRef.name : stateCode;
        unsupportedJurisdictions.push(displayName);
      } else {
        for (const layer of stateLayers) {
          resolvedLayers.push({
            layer,
            wms_url: BHUVAN_WMS_ROOT,
            applicable_jurisdiction: layer.state_name || stateCode,
            status: 'available',
          });
        }
      }
    }

    // Always include verified national layers matching workspace
    const nationalLayers = scopedCatalogue.filter(
      l => l.coverage === 'national'
    );
    for (const layer of nationalLayers) {
      resolvedLayers.push({
        layer,
        wms_url: BHUVAN_WMS_ROOT,
        applicable_jurisdiction: 'National',
        status: 'available',
      });
    }
  } else {
    // Case B: No jurisdiction filter passed (e.g. general layer discovery or national view)
    // Return all national layers plus state-scoped representative layers
    for (const layer of scopedCatalogue) {
      resolvedLayers.push({
        layer,
        wms_url: BHUVAN_WMS_ROOT,
        applicable_jurisdiction: layer.state_name || 'National',
        status: 'available',
      });
    }
  }

  return {
    resolved_layers: resolvedLayers,
    unsupported_jurisdictions: Array.from(new Set(unsupportedJurisdictions)),
    total_resolved: resolvedLayers.length,
    timestamp: new Date().toISOString(),
  };
}
